BROKERS = [ "Aldazabal y Cía.",
"Álvarez y Compañía Actividades Bursátiles",
"Banco Credicoop Cooperativo Limitado",
"Estructuras Financieras Regionales",
"Bacqué",
"Debursa ALyC",
"Mundo Bursátil",
"Bagnardi y Cía.",
"Proficio Investment",
"GMA Capital",
"Corsiglia y Cía.",
"Lares Capital",
"Compañía de Inversiones Bursátiles",
"Liebre Capital Suspendida preventivamente por CNV",
"Aurum Valores",
"Nuevo Chaco Bursátil",
"Arata",
"Capital Markets Argentina",
"ALYNK",
"SJB",
"Dracma",
"Benedit Bursátil",
"Grupo del Plata",
"Burplaza",
"Abut S.A.",
"Tarallo",
"Baires Bursátil",
"Nasini",
"Dellepiane y Cía.",
"Incapital",
"Option Securities",
"Agrosafe",
"Fernández Laya",
"ACA Valores",
"Falabella y Corsi Inversora",
"Giannoni",
"Cano Bursátil",
"Mateo y Marchioni S.B. Agente de Mercado",
"Tomar Inversiones",
"Maxinta Valores",
"Fescina y Cía.",
"Mediterránea Valores y Acciones",
"Bell Investments",
"BT Securities Argentina",
"RIG Valores",
"Novillo Saravia y Cía",
"Zofingen Securities",
"Pharos Capital",
"Valfinsa Bursátil",
"Banco de Corrientes",
"Comafi Bursátil",
"Petrini Valores",
"FX CAPITAL",
"Banco de la Nación Argentina",
"S&C Inversiones",
"GMC Valores",
"Intercapital",
"R. Mackintosh",
"Lynx Valores",
"Alchemy Valores",
"Seguí y Cía.",
"WIN SECURITIES",
"REM Bursátil",
"Max Capital",
"Montelatici y Cía.",
"Industrial Valores",
"NGA Inversiones",
"Macchi Valores",
"Bolsa de Comercio de La Plata",
"Maestro y Huerres",
"Navarro Viola y Cía.",
"AG Valores",
"Banco GGAL",
"Mar Del Plata Bursátil Agente de Liquidación y Compensación",
"Reba Compañía Financiera",
"Mills Capital Markets",
"Rabello y Cía.",
"Neix",
"Deal",
"Aeromar Valores",
"Banco Meridian",
"Banco de la Pampa",
"Santander Valores",
"Miguel J. Carril",
"Sociedad Militar Seguro de Vida Institución Mutualista",
"Los Tilos Bursátil",
"Cía. Gral. de Valores Mobiliarios",
"DHALMORE CAPITAL",
"Tutelar Bursátil",
"Banco Bica",
"Dinosaurio Bursátil",
"Eco Valores",
"Banco de Formosa",
"Rey López Bursátil",
"Schweber Securities",
"Agencia de Liquidación y Compensación Córdoba",
"Rava Bursátil",
"Momentum Capital Invesment",
"PGA Valores",
"Integrar",
"DRACMA INVESTMENTS",
"Servente y Cía.",
"Mario S. Fernandez y Cía",
"Compañía Global de Inversiones",
"STC Inversiones",
"Eurovalores",
"Rey Leyes Valores",
"Bull Market Brokers",
"Alfy Inversiones",
"Transatlántica S.A. Bursátil",
"Federal Bursátil",
"Tavelli y Cía.",
"Intervalores Group",
"Alycbur",
"Futuro Bursátil",
"BRIO Valores ALyC",
"Luis Domingo Trucco S. A.",
"Ubertone y Cía.",
"Rosental",
"Alcorta Valores",
"C.A. Teuly & Co.",
"Venini Núñez",
"Longo Elia Bursátil",
"Banco Julio",
"Bluelake Capital",
"GIO Bursátil",
"Quilmes Bursátil",
"Cono Sur Inversiones",
"Guor Investments",
"Sailing",
"Porzio Bursátil",
"Brancatelli",
"Bursátil Uspallata",
"Transacciones Agente de Valores",
"Morandi Valores",
"Euro Bursátil",
"Finance",
"CABSA",
"Versátil Inversiones y Transacciones",
"SECURITIES CAF ARGENTINA",
"BIBANK",
"SZWARC & CIA.",
"Banco de Inversión y Comercio Exterior",
"FINCO CAPITAL",
"Arpenta",
"Galicia Securities",
"Allaria Agrofinanzas",
"Cocos Capital",
"DMA Broker",
"Guarnieri Valores",
"VNR",
"Laguna",
"Stockbrokers",
"Veta Capital",
"Don Capital",
"Banco Coinag",
"Brubank",
"Cruzando Fronteras",
"Truegrit Capital",
"S.B.S Trading",
"Allaria",
"Nacion Bursátil",
"Portfolio Investment",
"Buenos Aires Valores",
"Banco de Servicios y Transacciones",
"Banco Mariva",
"Cucchiara y Cía.",
"Confidas Capital",
"Provincia Bursátil",
"Banco VOII",
"Becerra Bursátil",
"Banco Industrial",
"Macro Securities",
"Banco de Comercio",
"Latin Securities",
"Argentina Valores",
"Puente Hnos.",
"Banco de San Juan",
"Banco Supervielle",
"Banco BBVA Argentina",
"Cohen",
"Banco del Chubut",
"Patagonia Valores",
"Banco Comafi",
"Banco de la Provincia de Buenos Aires",
"Global Valores",
"Five Corporation",
"Bahía Blanca Sociedad de Bolsa",
"Banco de Valores",
"BTU Valores",
"Metrocorp Valores",
"TPCG Valores",
"Inviu",
"Parakeet Capital",
"ADCAP Securities Argentina",
"Nuevo Banco de Entre Ríos",
"Mariva Bursátil",
"Nuevo Banco de Santa Fé",
"Rosario Valores",
"Banco Santander Argentina",
"Banco de la Provincia de Córdoba",
"Arpenta Valores",
"Industrial and Commercial Bank of China (Argentina)",
"Banco Hipotecario",
"Invertir Online",
"Bolsa de Comercio del Chaco",
"Ualintec Capital",
"Prosecurities",
"Facimex Valores",
"BMA Valores",
"Napoli Inversiones",
"BACS Banco de Crédito y Securitización",
"QUANT CAPITAL",
"BACS Administradora de Activos",
"Banco Macro",
"Invertir en Bolsa",
"Centaurus Securities",
"Banco de Galicia y Buenos Aires",
"Banco de la Ciudad de Buenos Aires",
"CITIBANK N.A.",
"Nix Valores",
"Criteria WM",
"Balanz",
"STONEX Securities",
"Banco Patagonia",
"Banco de Santa Cruz",
"Consultatio Investments",
"PP Inversiones",
"BTG Pactual Argentina",
"JPMorgan Chase Bank NA (Suc. Bs. As.)",
"Banco CMF",
"Banco Piano",
"Luxfin Valores",
"DA Valores",
"Bank of China Limited Sucursal Buenos Aires",
"Banco del Sol",
"Otro" ]
